### ISSUE TITLE
Extrinsic Transformation

### ISSUE THREAD

**Issue by TheRealKaufmann** [christopherdoer/rio#1]
Hi,

thank you for this great project! Just one question: where can I find/change the extrinsic configuration between radar and IMU?

I know that you perform online calibration, but is there an initial guess or something like that required? And where do I find that?

Thanks,
Tom

**Comment by christopherdoer** [comment]
Hi Tom,   
Thanks, glad to hear you like this project!
Yes, a rough initial guess of the extrinsic calibration is required. This is done with a few ros parameters: 
- translation (in body frame): l_b_r_x, l_b_r_y, l_b_r_z
- rotation (radar to body frame): q_b_r_w, q_b_r_x, q_b_r_y, q_b_r_z

Take a look at [calib_vicon_dataset.yaml](https://github.com/christopherdoer/rio/blob/main/demo_datasets/calib_vicon_dataset.yaml) which is loaded by [demo_datasets_ekf-rio_rosbag.launch](https://github.com/christopherdoer/rio/blob/main/ekf_rio/launch/demo_datasets_ekf-rio_rosbag.launch).
Hope that helps!

**Comment by TheRealKaufmann** [comment]
Thank you very much for your answer! 
Just one more question: Do you think a IMU with a rate of 200hz would be sufficient. I saw that the datasets are recorded with a 400hz imu.

Thanks!

**Comment by christopherdoer** [comment]
Yes, 200 Hz should work as well. Most important is a small yaw rate bias drift if you plan to use ekf_rio, since yaw is based on the IMU measurements only. That's is a little different with ekf_yrio which can compensate for a yaw rate bias drift assuming that the environment follows the Manhattan world assumption.

**Comment by TheRealKaufmann** [comment]
Thank you!
