### ISSUE TITLE
CMake errors

### ISSUE THREAD

**Issue by ram-bhaskara** [christopherdoer/rio#12]
Is it possible to catkin_make all the packages? I get the following cmake errors (for all the packages) when trying to do so.

```
CMake Error at rio/x_rio/CMakeLists.txt:38 (add_custom_target):
  add_custom_target cannot create target "headers" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/user/catkin_ws/src/rio/reve/radar_ego_velocity_estimator".  See
  documentation for policy CMP0002 for more details.
```
Is it possible to build only one package, **x_rio**? Assuming that **reve** is to be necessarily built for all the variants.

**Comment by christopherdoer** [comment]
So far, I have only used  `catkin build`. Does that work for you? 

I am not sure what you mean with building only one package. Using `catkin build x_rio --cmake-args -DCMAKE_BUILD_TYPE=Release` only builds x_rio and the required dependencies (rio_utils, reve).
Hope that helps!

**Comment by ram-bhaskara** [comment]
catkin_build worked! thanks! I was trying to build using catkin_make (like for REVE).
