### ISSUE TITLE
Running without trigger

### ISSUE THREAD

**Issue by cmakelabs** [christopherdoer/rio#17]
I would like to ask, is it possible to run the node without having `topic_radar_trigger`, It is just that the dataset I am using is custom, and the radars there do not have a trigger topic

**Comment by joelsa** [comment]
Yes, just supply the corresponding config option to the launcher:

~~~[shell]
roslaunch package name launch_file_name.launch run_without_radar_trigger:=True
~~~

However, if you check the x-rio paper (x-RIO: Radar Inertial Odometry with Multiple
Radar Sensors and Yaw Aiding), then it states:

> Thus, the received radar scans have a varying time offset which scales with the radar scan size. Our implementation should be used for online navigation even under dynamic motion. Thus, a real-time navigation system is required. Hence, a delayed orocessing (e.g., 100 ms) is not possible. Therefore, each radar sensor is triggered via a dedicated hardware trigger signal. Consequently, the exact time stamps of the corresponding radar scans are known

So YMMV.

**Comment by cmakelabs** [comment]
Thank you for the elaborate answer
