### ISSUE TITLE
Error: Ignoring transform for child_frame_id - when running demo datasets

### ISSUE THREAD

**Issue by visocopter** [christopherdoer/rio#2]
Hi,

when I try to run the demos, I always get the following error:

Ignoring transform for child_frame_id "base_link" from authority "unknown_publisher" because of a nan value in the transform (-nan -nan -nan) (0,000000 0,000000 0,000000 1,000000)
Ignoring transform for child_frame_id "radar" from authority "unknown_publisher" because of a nan value in the transform (-nan -nan -nan) (0,000000 0,000000 0,000000 1,000000)

Can you help me please?

**Comment by christopherdoer** [comment]
Hi,
Thanks for opening an issue! Yep, that bug was introduced lately. I just fixed it in the main branch, is it working now?
Best,
Christopher

**Comment by visocopter** [comment]
Yes thank you that worked!
