### ISSUE TITLE
issues with consistent pointcloud

### ISSUE THREAD

**Issue by visocopter** [christopherdoer/rio#5]
Hi,

I am still trying to generate data similar to your datasets, to contribute. 

I managed to modify the ti_mmwave_ros_pkg to match your message formats. Also the external triggering of the IWR6843AOPEVM is done via a microcontroller, which also collects IMU mesaurements with accurate timestamps.

But there is one problem: 
In your datasets, it seems like the pointcloud and other data is always publishing with a consistent rate of 10hz. Even though I am using exernal triggering, if there is no movement of the sensor, no data will publish. How did you solve this problem? I can see in the pointcloud, that when you are standing still, a lot of points still get published over and over again at 10hz.

It would be awesome if you could help out again!

Thanks

**Comment by christopherdoer** [comment]
Hi,
That sounds good! Seems like you setup is quite similar to what I am using. 
You might have some issues with the radar config. Have a look at the "cfarCfg" part of the radar config. For instance, I used 8dB for the range direction and 20dB for the Doppler direction. If the detection threshold for the range direction is set too high, I also get empty point clouds during standstill. Hope that helps!

**Comment by joelsa** [comment]
@visocopter Would you be able to share your modifications to the ti_mmwave_ros_pkg and/or your code to interface the MCU? E.g. to push them into a repository?

**Comment by visocopter** [comment]
Hi @christopherdoer, 

thanks so much for that suggestion. We will definitly try that. Also, did you configure the radar for best velocity resolution or best range resolution?

Thanks!

**Comment by visocopter** [comment]
Hi @joelsa,

we (@TheRealKaufmann and I) might publish the modified driver as well as the microcontroller script. But its not done yet and there are still some bugs. Once everything works, we might publish it and write a short tutorial on how to generate datasets suitable for RIO.

**Comment by christopherdoer** [comment]
Sorry for the late reply, I was on vacation... 
There are some updates regarding the ti_mmwave_rospkg support and non triggered radar scans!
@joelsa @visocopter  check out [issue 4](https://github.com/christopherdoer/rio/issues/4) and [issue 6](https://github.com/christopherdoer/rio/issues/6).

**Comment by visocopter** [comment]
Thanks!
