### ISSUE TITLE
Question about imu attitude

### ISSUE THREAD

**Issue by Ericwen2001** [christopherdoer/rio#9]
Hi, this is a very interesting project. I found x_rio give a very fast downward trajectory in rviz in our own data even I set n_radar:=0
I suspect it's because in our setting the gravity acts on the y axis of imu instead of z axis in your demo dataset. Is this a reasonable explanation? If it is, how can I run it successfully?
![image](https://user-images.githubusercontent.com/61090824/180256749-fa065ed0-afc9-4622-9a10-56f3f39e6579.png)
![image](https://user-images.githubusercontent.com/61090824/180258374-39b65bde-e9f2-41d4-a893-e209772cb5ee.png)

Many thanks.

**Comment by Ericwen2001** [comment]
Or this might because the platform is not stationary during the 10s initialisation?

**Comment by christopherdoer** [comment]
Thanks for trying out RIO!
The initial attitude should not be a problem as this is initialized. The default initialization time is 10s. If the IMU is not stationary, you'll see bad results. You can decrease this parameter (T_init) to lower values. This will, however, increase the yaw drift. Also make sure, that the rotational part of the extrinsic transform (radar to IMU) is roughly correct (within 10 deg) to get good results. 

Does that work for you?

**Comment by Ericwen2001** [comment]
No, I haven't found the reason why currently x_rio don't give a reasonable result in our platform, perhaps it's because we don't have trigger. Apart from this, in some cases this error appears `[ERROR] [1658762963.187114704]: Ignoring transform for child_frame_id "imu" from authority "unknown_publisher" because of a nan value in the transform (nan nan nan) (0.000000 0.000000 0.000000 1.000000)
` alongside `[ INFO] [1658762963.176955266]: [EkfRioFilter]: Initialized attitude: -88.6004deg, nandeg
`
arcsin return a nan in the initialisation. I guess this is a bug?

**Comment by christopherdoer** [comment]
In low dynamic scenarios, RIO w/o triggering should still give good results.

Yep, that's a bug for sure, thanks for pointing out! 
Should be fixed in the branch [feature_fix_initialization](https://github.com/christopherdoer/rio/tree/feature_fix_initialization).

Hope that works!

**Comment by christopherdoer** [comment]
The initialization fix is merged into the main branch. Is it working with your setup @Ericwen2001?

**Comment by Ericwen2001** [comment]
Yes, the initialization bug is indeed fixed. Thanks.
